<script src="{{ asset('plugins/jquery-3.7.1/jquery-3.7.1.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-5.3.3/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('plugins/sweetalert2-11.11.1/sweetalert2-11.11.1.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-2.0.8/js/datatables.min.js') }}"></script>
<script src="{{ asset('plugins/fontawesome-6.5.2/js/all.min.js') }}"></script>
<script src="{{ asset('plugins/select2-4.1.0/js/select2.full.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>
<script src="{{ asset('dist/js/common.js') }}"></script>
<script src="{{ asset('dist/js/' . trim($__env->yieldContent('custom-js')) ) }}"></script>
